services:
  mysql:
    image: mysql:8.0
    container_name: mysql_pet
    ports:
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web-network

  redis:
    image: redis:latest
    container_name: redis_pet
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - web-network

  kafka:
    image: 'bitnami/kafka:3.7.0'
    container_name: kafka_pet
    hostname: kafka
    ports:
      - '9093:9092'
      - '9095:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - web-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch_pet
    hostname: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - bootstrap.memory_lock=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9200/_cluster/health" ]
      interval: 30s
      timeout: 15s
      retries: 15
      start_period: 100s
    ports:
      - "9201:9200"
      - "9301:9300"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - web-network

  backend:
    build:
      context: ./BackEnd
      dockerfile: Dockerfile
    container_name: backend_pet
    ports:
      - "8089:8089"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USERNAME=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      - SPRING_MAIL_HOST=${SPRING_MAIL_HOST}
      - SPRING_MAIL_PORT=${SPRING_MAIL_PORT}
      - SPRING_MAIL_USERNAME=${SPRING_MAIL_USERNAME}
      - SPRING_MAIL_PASSWORD=${SPRING_MAIL_PASSWORD}
      - SPRING_MAIL_FROM=${SPRING_MAIL_FROM}
      # - JWT_SIGNER_KEY=${JWT_SIGNER_KEY}
      - JWT_VALID_DURATION=${JWT_VALID_DURATION}
      - JWT_REFRESHABLE_DURATION=${JWT_REFRESHABLE_DURATION}
      - APP_JWT_SECRET=${APP_JWT_SECRET}
      - URIS=elasticsearch:9200
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - GOOGLE_REDIRECT_URL=${GOOGLE_REDIRECT_URL}
      - GOOGLE_SCOPE=${GOOGLE_SCOPE}
      # - CLOUD_NAME=${CLOUD_NAME}
      # - CLOUD_API_KEY=${CLOUD_API_KEY}
      # - CLOUD_API_SECRET=${CLOUD_API_SECRET}
      - USER_INFO_URI=${USER_INFO_URI}
      - SPRING_SERVLET_MULTIPART_ENABLED=true
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=100MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=100MB
      - CLOUDINARY_CLOUD_NAME=${CLOUD_NAME}
      - CLOUDINARY_API_KEY=${CLOUD_API_KEY}
      - CLOUDINARY_API_SECRET=${CLOUD_API_SECRET}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8089/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - web-network
    command: java -jar app.jar --debug
volumes:
  redis_data:
    driver: local
  elastic_data:
    driver: local
  mysql_data:
    driver: local

networks:
  web-network:
    driver: bridge
